# PyHelios Configuration File
# 
# This configuration file allows you to specify plugin selection and build
# options for PyHelios without using command-line arguments.

# Plugin configuration
plugins:
  # Selection mode: "profile", "explicit", or "auto"
  selection_mode: "profile"
  
  # Profile to use when selection_mode is "profile"
  # Available profiles: minimal, standard, gpu-accelerated, research, production, 
  #                    visualization, sensing, physics, development
  profile: "standard"
  
  # Explicit plugin list when selection_mode is "explicit"  
  # Available plugins: weberpenntree, canopygenerator, radiation, visualizer,
  #                   lidar, aeriallidar, energybalance, photosynthesis, leafoptics,
  #                   stomatalconductance, boundarylayerconductance, plantarchitecture,
  #                   planthydraulics, solarposition, syntheticannotation,
  #                   parameteroptimization, voxelintersection, collisiondetection,
  #                   projectbuilder
  explicit_plugins:
    - weberpenntree
    - canopygenerator
    - visualizer
    - energybalance
  
  # Plugins to exclude from selection (applies to all modes)
  excluded_plugins:
    - projectbuilder  # Exclude GUI builder by default
  
  # Include optional dependencies (plugins that are dependencies of selected plugins)
  include_optional: true
  
  # Platform-specific overrides
  platform_specific:
    windows:
      # Windows can support GPU plugins
      additional_plugins:
        - radiation
    linux:
      # Linux can support GPU plugins
      additional_plugins:
        - radiation
        - lidar
    macos:
      # macOS has limited GPU support
      excluded_plugins:
        - radiation
        - aeriallidar
        - collisiondetection

# Build configuration  
build:
  # CMake build type: Release, Debug, RelWithDebInfo, MinSizeRel
  build_type: "Release"
  
  # Additional CMake arguments
  cmake_args:
    - "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
    - "-DCMAKE_CXX_FLAGS=-fPIC"
  
  # Number of parallel build jobs (0 = auto-detect)
  parallel_jobs: 0
  
  # Verbose build output
  verbose: false

# System configuration
system:
  # Force mock mode (disable native library functionality)
  force_mock_mode: false
  
  # Environment variables to set during build
  environment:
    # Uncomment to disable GPU features
    # PYHELIOS_EXCLUDE_GPU: "1"
    
    # Uncomment to enable development mode  
    # PYHELIOS_DEV_MODE: "1"

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # Enable plugin detection logging
  plugin_detection: true
  
  # Enable build process logging
  build_logging: true

# Examples of different configurations:

# Example 1: Minimal configuration for development
# plugins:
#   selection_mode: "profile"
#   profile: "development"

# Example 2: GPU-accelerated research configuration
# plugins:
#   selection_mode: "profile" 
#   profile: "research"
#   excluded_plugins:
#     - projectbuilder

# Example 3: Custom plugin selection
# plugins:
#   selection_mode: "explicit"
#   explicit_plugins:
#     - weberpenntree
#     - canopygenerator
#     - radiation
#     - visualizer
#     - energybalance
#     - photosynthesis

# Example 4: Cross-platform safe configuration
# plugins:
#   selection_mode: "profile"
#   profile: "standard"
#   excluded_plugins:
#     - radiation      # Exclude GPU-dependent plugins
#     - aeriallidar
#     - collisiondetection