"""
W3 -- Dataset generation. Episodes -> compressed shards + manifest.json.

## Structure of the dataset

Two coupled action channels, generated from the SAME orchard instances so the
world model sees one consistent world:

**View episodes** (`family` in row_traversal / orbit / random_walk)
    One episode = one camera trajectory of `n_steps` poses at a FIXED growth
    stage. Because the scene is static within a stage, the whole trajectory is
    one camera batch -> one radiative solve. This is the efficiency trick the
    plan is built on, and W1 measured it: the solve costs ~5.2 s whether 1 or
    256 cameras are registered.

**Growth episodes** (`family` = "growth")
    One episode = ONE camera pose held fixed while the orchard is advanced
    through the growth schedule. `a_grow` is the number of days advanced to the
    next frame; `a_view` is zero. Generated by rendering a fixed probe rig at
    every growth stage of the same orchard and then transposing: stage-major
    renders become pose-major episodes at no extra render cost.

## Why growth stages come from advanceTime, not from separate builds

W0c measured both paths to age 590 d from seed 10000 and they agree: identical
primitive counts for every organ, leaf area differing by 1.4e-5 m² out of 110 m²
(1.3e-7 relative) and shoot area by 0.017 m² out of 111 m² (1.5e-4 relative).
The advanceTime path costs ~2.5 s per stage against ~7-37 s for a rebuild, so
the generator builds ONCE at the first stage age and advances.

## Growth schedule

W0b measured the apple model's life cycle on a 10-day grid and found it is
piecewise constant, not smooth: nothing changes between 580 d and 730 d, and
leaves+fruit are gone by 740 d. The only window where geometry actually moves is
roughly 540-580 d. The default schedule therefore lives inside that window at
5-day resolution. This is a real, measured restriction on the growth channel, not
a design preference -- see FINDINGS.md.

## Splits

Split is by ORCHARD SEED, never by frame -- frames inside a trajectory are near
duplicates and a frame-level split would leak (Phase 6 caught exactly that class
of bug in the gsplat pipeline). `orchard.TRAIN_SEEDS/VAL_SEEDS/TEST_SEEDS` are
disjoint ranges, verified by `verify_seed_split()`.
"""

import argparse
import gc
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from yogesh_dev.world_model.orchard import (
    build_orchard, orchard_extent, TRAIN_SEEDS, VAL_SEEDS, TEST_SEEDS, verify_seed_split,
)
from yogesh_dev.world_model.render import ObservationRig, SKY_SEMANTIC_ID, SKY_RGB
from yogesh_dev.world_model import actions as A

DEFAULT_OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output", "dataset")

# Measured growth window (W0b/W0c). Stage 0 is the build age; the rest are
# reached by advanceTime.
GROWTH_STAGES = [540.0, 545.0, 550.0, 555.0, 560.0, 565.0, 570.0, 580.0]

VIEW_FAMILIES = ("row_traversal", "orbit", "random_walk")
SEMANTIC_REMAP_SKY = 6   # storage class id for sky (255 is wasteful as a class index)


def _semantic_for_storage(sem_u8):
    """render.py emits sky as 255; store it as class 6 so the array is a dense
    0..6 class index that a cross-entropy head can consume directly."""
    out = sem_u8.copy()
    out[out == SKY_SEMANTIC_ID] = SEMANTIC_REMAP_SKY
    return out


def _fruit_visibility(sem_u8):
    """Fraction of pixels labelled fruit -- the scalar the fruit head predicts."""
    return float((sem_u8 == 1).mean())


def _n_visible_fruit(inst):
    v = inst[inst >= 0]
    return int(len(np.unique(v))) if v.size else 0


def frames_to_arrays(frames, states, view_actions, grow_actions):
    """Stack a list of per-frame dicts into the on-disk episode arrays."""
    sem = np.stack([_semantic_for_storage(f["semantic"]) for f in frames])
    return {
        "rgb": np.stack([f["rgb"] for f in frames]).astype(np.uint8),
        "depth": np.stack([f["depth"] for f in frames]).astype(np.float16),
        "semantic": sem.astype(np.uint8),
        "instance": np.stack([f["instance"] for f in frames]).astype(np.int32),
        "pose": np.stack([f["pose"] for f in frames]).astype(np.float32),
        "state": np.asarray(states, dtype=np.float32),
        "a_view": np.asarray(view_actions, dtype=np.float32),
        "a_grow": np.asarray(grow_actions, dtype=np.float32).reshape(-1, 1),
        "fruit_vis": np.asarray([_fruit_visibility(f["semantic"]) for f in frames],
                                dtype=np.float32),
        "n_fruit_visible": np.asarray([_n_visible_fruit(f["instance"]) for f in frames],
                                      dtype=np.int32),
    }


def write_episode(out_dir, name, arrays, meta):
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"{name}.npz")
    np.savez_compressed(path, **arrays, meta=json.dumps(meta))
    return path, os.path.getsize(path)


def generate_orchard(seed, split, out_root, n_steps=128, families=VIEW_FAMILIES,
                     stages=GROWTH_STAGES, n_growth_probes=16, exposure_scale=None,
                     orientation="fliplr", resolution=(128, 128), sun_zenith=30.0,
                     sun_azimuth=120.0, n_cameras=None, log=print):
    """Generate every episode for ONE orchard seed. Returns a list of episode records.

    All view families are rendered at EVERY growth stage, so the view channel and
    the growth channel share the same underlying orchards rather than being two
    unrelated datasets.
    """
    ext = orchard_extent()
    n_cameras = n_cameras or max(n_steps, n_growth_probes)
    out_dir = os.path.join(out_root, split)
    records = []

    t_build0 = time.time()
    orch = build_orchard(seed=seed, age_days=stages[0])
    log(f"    build age={stages[0]}: {orch.n_primitives()} prims in {orch.build_time_s:.1f}s")

    # Fixed probe poses for the growth channel: identical at every stage, seeded
    # off the orchard seed so different orchards get different (but reproducible)
    # probe viewpoints.
    probe_rng = np.random.default_rng(seed * 7919 + 13)
    probe_states = A.sample_random_walk(n_growth_probes, ext, probe_rng)
    probe_poses = A.states_to_poses(probe_states)

    rig = None
    try:
        rig = ObservationRig(orch, n_cameras=n_cameras, resolution=resolution,
                             sun_zenith=sun_zenith, sun_azimuth=sun_azimuth,
                             exposure_scale=exposure_scale)
        rig.open()
        rig._orientation = orientation

        growth_frames_by_stage = []
        timings = {"solve_s": 0.0, "read_s": 0.0, "grow_s": 0.0, "write_s": 0.0}

        for si, stage_age in enumerate(stages):
            if si > 0:
                dt = stage_age - stages[si - 1]
                t0 = time.time()
                orch.grow(dt)
                rig.radiation.updateGeometry()
                timings["grow_s"] += time.time() - t0

            # ---- view episodes at this stage --------------------------------
            for family in families:
                traj_seed = int(seed * 1000003 + si * 101 + VIEW_FAMILIES.index(family))
                states, a_view, _ = A.sample_trajectory(family, n_steps, ext, traj_seed)
                poses = A.states_to_poses(states)
                frames, tm = rig.render_batch(poses)
                timings["solve_s"] += tm["solve_s"]
                timings["read_s"] += tm["read_s"]
                arrays = frames_to_arrays(frames, states, a_view, np.zeros(n_steps))
                meta = {
                    "episode_type": "view", "family": family, "orchard_seed": int(seed),
                    "split": split, "stage_index": si, "age_days": float(stage_age),
                    "traj_seed": traj_seed, "n_steps": int(n_steps),
                    "resolution": list(resolution), "exposure_scale": float(rig.exposure_scale),
                    "sun_zenith": sun_zenith, "sun_azimuth": sun_azimuth,
                    "pitch_deg": A.DEFAULT_PITCH_DEG, "orientation": orientation,
                    "hfov_deg": rig.hfov_deg, "sky_rgb": list(SKY_RGB),
                    "n_primitives": orch.n_primitives(),
                }
                t0 = time.time()
                path, nbytes = write_episode(
                    out_dir, f"view_s{seed}_g{si}_{family}", arrays, meta)
                timings["write_s"] += time.time() - t0
                records.append({**meta, "path": os.path.relpath(path, out_root),
                                "bytes": nbytes})

            # ---- growth probe renders at this stage --------------------------
            gframes, tm = rig.render_batch(probe_poses)
            timings["solve_s"] += tm["solve_s"]
            timings["read_s"] += tm["read_s"]
            growth_frames_by_stage.append(gframes)
            log(f"    stage {si} age={stage_age:.0f}d prims={orch.n_primitives()} "
                f"solve={tm['solve_s']:.1f}s")

        # ---- transpose stage-major -> pose-major growth episodes -------------
        n_stages = len(stages)
        grow_dts = [stages[i + 1] - stages[i] for i in range(n_stages - 1)] + [0.0]
        for p in range(n_growth_probes):
            frames = [growth_frames_by_stage[s][p] for s in range(n_stages)]
            states = np.repeat(probe_states[p][None, :], n_stages, axis=0)
            arrays = frames_to_arrays(frames, states, np.zeros((n_stages, 4)), grow_dts)
            arrays["age_days"] = np.asarray(stages, dtype=np.float32)
            meta = {
                "episode_type": "growth", "family": "growth", "orchard_seed": int(seed),
                "split": split, "probe_index": p, "n_steps": n_stages,
                "stage_ages": list(stages), "resolution": list(resolution),
                "exposure_scale": float(rig.exposure_scale),
                "sun_zenith": sun_zenith, "sun_azimuth": sun_azimuth,
                "pitch_deg": A.DEFAULT_PITCH_DEG, "orientation": orientation,
                "hfov_deg": rig.hfov_deg, "sky_rgb": list(SKY_RGB),
            }
            t0 = time.time()
            path, nbytes = write_episode(out_dir, f"growth_s{seed}_p{p}", arrays, meta)
            timings["write_s"] += time.time() - t0
            records.append({**meta, "path": os.path.relpath(path, out_root), "bytes": nbytes})

        timings["total_s"] = time.time() - t_build0
        timings["build_s"] = orch.build_time_s
        for r in records:
            r["orchard_timings"] = timings
    finally:
        if rig is not None:
            rig.close()
        orch.close()
        gc.collect()
    return records


def calibrate_once(seed, stage_age, resolution, sun_zenith, sun_azimuth, log=print):
    """Compute the ONE global exposure scale + the pixel orientation, from a
    single orchard. Every episode in the dataset then uses these verbatim."""
    ext = orchard_extent()
    orch = build_orchard(seed=seed, age_days=stage_age)
    try:
        rig = ObservationRig(orch, n_cameras=16, resolution=resolution,
                             sun_zenith=sun_zenith, sun_azimuth=sun_azimuth)
        rig.open()
        rng = np.random.default_rng(0)
        cal_states = np.concatenate([
            A.sample_row_traversal(8, ext, rng),
            A.sample_random_walk(8, ext, rng)], axis=0)
        cal_poses = A.states_to_poses(cal_states)
        orient = rig.calibrate_orientation(cal_poses)
        expo = rig.calibrate_exposure(cal_poses, percentile=99.0)
        rig.close()
        log(f"  calibration: orientation={orient['applied']} exposure={expo['exposure_scale']:.5f}")
        return orient, expo
    finally:
        orch.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--n-train", type=int, default=24)
    ap.add_argument("--n-val", type=int, default=4)
    ap.add_argument("--n-test", type=int, default=4)
    ap.add_argument("--n-steps", type=int, default=128)
    ap.add_argument("--n-growth-probes", type=int, default=16)
    ap.add_argument("--stages", type=int, default=len(GROWTH_STAGES))
    ap.add_argument("--families", default=",".join(VIEW_FAMILIES))
    ap.add_argument("--resolution", type=int, default=128)
    ap.add_argument("--sun-zenith", type=float, default=30.0)
    ap.add_argument("--sun-azimuth", type=float, default=120.0)
    ap.add_argument("--resume", action="store_true",
                    help="skip orchards whose episodes are already on disk")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    res = (args.resolution, args.resolution)
    stages = GROWTH_STAGES[:args.stages]
    families = tuple(f for f in args.families.split(",") if f)
    log_path = os.path.join(args.out, "generate_log.txt")
    logf = open(log_path, "a")

    def log(m):
        print(m, flush=True)
        logf.write(str(m) + "\n")
        logf.flush()

    log("=" * 78)
    log(f"W3 generate  {time.strftime('%Y-%m-%d %H:%M:%S')}")
    log(f"  out={args.out} stages={stages} families={families} "
        f"n_steps={args.n_steps} probes={args.n_growth_probes} res={res}")
    log(f"  seed split check: {verify_seed_split()}")

    orient, expo = calibrate_once(list(TRAIN_SEEDS)[0], stages[0], res,
                                  args.sun_zenith, args.sun_azimuth, log=log)

    plan = ([(s, "train") for s in list(TRAIN_SEEDS)[:args.n_train]]
            + [(s, "val") for s in list(VAL_SEEDS)[:args.n_val]]
            + [(s, "test") for s in list(TEST_SEEDS)[:args.n_test]])

    manifest_path = os.path.join(args.out, "manifest.json")
    manifest = {"created": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "config": {"stages": stages, "families": list(families),
                           "n_steps": args.n_steps, "n_growth_probes": args.n_growth_probes,
                           "resolution": list(res), "sun_zenith": args.sun_zenith,
                           "sun_azimuth": args.sun_azimuth,
                           "exposure_scale": expo["exposure_scale"],
                           "orientation": orient["applied"],
                           "semantic_classes": {0: "other/ground", 1: "fruit", 2: "leaf",
                                                 3: "shoot", 4: "petiole", 5: "peduncle",
                                                 6: "sky"},
                           "depth_sky_sentinel": -1.0,
                           "sky_rgb": list(SKY_RGB)},
                "calibration": {"orientation": orient, "exposure": expo},
                "splits": {"train": [], "val": [], "test": []},
                "episodes": []}
    if args.resume and os.path.isfile(manifest_path):
        with open(manifest_path) as f:
            manifest = json.load(f)
        log(f"  resuming: {len(manifest['episodes'])} episodes already recorded")

    done_seeds = {(e["orchard_seed"], e["split"]) for e in manifest["episodes"]}
    t_all = time.time()
    for i, (seed, split) in enumerate(plan):
        if args.resume and (seed, split) in done_seeds:
            log(f"  [{i+1}/{len(plan)}] seed {seed} ({split}) already done, skipping")
            continue
        log(f"  [{i+1}/{len(plan)}] orchard seed {seed} ({split})")
        t0 = time.time()
        recs = generate_orchard(
            seed, split, args.out, n_steps=args.n_steps, families=families,
            stages=stages, n_growth_probes=args.n_growth_probes,
            exposure_scale=expo["exposure_scale"], orientation=orient["applied"],
            resolution=res, sun_zenith=args.sun_zenith, sun_azimuth=args.sun_azimuth, log=log)
        manifest["episodes"].extend(recs)
        if seed not in manifest["splits"][split]:
            manifest["splits"][split].append(seed)
        with open(manifest_path, "w") as f:
            json.dump(manifest, f, indent=1)
        n_fr = sum(r["n_steps"] for r in recs)
        mb = sum(r["bytes"] for r in recs) / 1e6
        log(f"    -> {len(recs)} episodes, {n_fr} frames, {mb:.0f} MB, {time.time()-t0:.0f}s")

    total_frames = sum(e["n_steps"] for e in manifest["episodes"])
    total_bytes = sum(e["bytes"] for e in manifest["episodes"])
    manifest["totals"] = {"n_episodes": len(manifest["episodes"]),
                          "n_frames": total_frames, "bytes": total_bytes,
                          "wall_clock_s": time.time() - t_all}
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=1)
    log(f"DONE: {len(manifest['episodes'])} episodes, {total_frames} frames, "
        f"{total_bytes/1e9:.2f} GB in {time.time()-t_all:.0f}s")
    logf.close()
    return manifest


if __name__ == "__main__":
    try:
        m = main()
        try:
            sys.path.insert(0, "/home/yogesh/PyHelios")
            from notify_slack import notify_slack
            notify_slack(f"World model W3 dataset generation done: "
                         f"{m['totals']['n_frames']} frames, "
                         f"{m['totals']['bytes']/1e9:.2f} GB, "
                         f"{m['totals']['wall_clock_s']/60:.0f} min")
        except Exception:
            pass
    except Exception:
        import traceback
        traceback.print_exc()
        try:
            sys.path.insert(0, "/home/yogesh/PyHelios")
            from notify_slack import notify_slack
            notify_slack(f"World model W3 FAILED: {traceback.format_exc()[-1200:]}")
        except Exception:
            pass
        raise
