"""
W0c -- growth-channel feasibility inside the *real* growth window.

W0's advanceTime measurement started at 650 d, which W0b then showed is inside a
completely frozen region of the apple model's life cycle (every organ count and
area is bit-identical from 580 d to 730 d). So that measurement answered "how
much does advanceTime cost" but not "does advanceTime actually change anything".

This script re-runs the growth channel where W0b says the growth is:
  540 d (budbreak) -> 590 d (canopy + fruit fully expanded), in 5-day steps.

It answers two questions that gate the whole growth channel:

  Q1  Cost: what does `advanceTime(dt)` cost at 20-tree scale in the window
      where geometry is actually changing (as opposed to the frozen window,
      where W0 measured 0.9-2.8 s)?

  Q2  Equivalence: is `build(age=A) -> advanceTime(B-A)` the same orchard as
      `build(age=B)`? If yes, the growth channel can be generated by ONE build
      plus cheap advances instead of one full ~37 s build per growth stage --
      an order-of-magnitude difference in dataset cost. If no, the two paths are
      different orchards and the dataset must say which one it used.

Run:
    /home/yogesh/anaconda3/envs/helios/bin/python -m yogesh_dev.world_model.run_w0c
"""

import argparse
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from yogesh_dev.world_model.orchard import build_orchard

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output", "w0")


def _geom_signature(orch):
    """Cheap but discriminating summary of the orchard's current geometry."""
    ctx, uu = orch.context, orch.all_uuids()
    out = {"n_primitives": len(uu)}
    for organ in ("leaf", "shoot", "fruit", "petiole", "peduncle"):
        m = ctx.filterPrimitivesByData(uu, "object_label", organ)
        out[f"n_{organ}_prims"] = len(m)
        out[f"area_{organ}_m2"] = float(sum(ctx.getPrimitiveArea(u) for u in m)) if m else 0.0
    lo, hi = orch.bounds()
    out["bounds_min"] = lo.tolist()
    out["bounds_max"] = hi.tolist()
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=10000)
    ap.add_argument("--start-age", type=float, default=540.0)
    ap.add_argument("--dt", type=float, default=5.0)
    ap.add_argument("--n-steps", type=int, default=10)
    args = ap.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    lines = []

    def log(m):
        print(m, flush=True)
        lines.append(str(m))

    log("=" * 78)
    log("W0c -- growth channel inside the real growth window")
    log("=" * 78)

    # -- Q1: advanceTime cost + geometry change in the growth window ----------
    log(f"\n[Q1] build at {args.start_age}d then advanceTime({args.dt}) x {args.n_steps}")
    orch = build_orchard(seed=args.seed, age_days=args.start_age)
    steps = []
    try:
        sig = _geom_signature(orch)
        steps.append({"age": orch.age_days, "dt": 0.0, "seconds": orch.build_time_s,
                      "path": "build", **sig})
        log(f"  age={orch.age_days:6.1f}  build {orch.build_time_s:6.2f}s  "
            f"prims={sig['n_primitives']:7d}  leafA={sig['area_leaf_m2']:8.2f}  "
            f"fruitA={sig['area_fruit_m2']:8.3f}")
        for _ in range(args.n_steps):
            el = orch.grow(args.dt)
            sig = _geom_signature(orch)
            steps.append({"age": orch.age_days, "dt": args.dt, "seconds": el,
                          "path": "advanceTime", **sig})
            log(f"  age={orch.age_days:6.1f}  grow  {el:6.2f}s  "
                f"prims={sig['n_primitives']:7d}  leafA={sig['area_leaf_m2']:8.2f}  "
                f"fruitA={sig['area_fruit_m2']:8.3f}")
        grow_end_age = orch.age_days
        grow_end_sig = _geom_signature(orch)
    finally:
        orch.close()

    grow_times = [s["seconds"] for s in steps if s["path"] == "advanceTime"]
    log(f"  advanceTime cost in-window: mean={np.mean(grow_times):.2f}s "
        f"min={np.min(grow_times):.2f}s max={np.max(grow_times):.2f}s "
        f"(vs {steps[0]['seconds']:.1f}s for a full build)")

    # how much does the geometry actually move between consecutive stages?
    deltas = []
    for a, b in zip(steps[:-1], steps[1:]):
        deltas.append({
            "from_age": a["age"], "to_age": b["age"],
            "d_prims": b["n_primitives"] - a["n_primitives"],
            "d_leaf_area": b["area_leaf_m2"] - a["area_leaf_m2"],
            "d_fruit_area": b["area_fruit_m2"] - a["area_fruit_m2"],
            "identical": (b["n_primitives"] == a["n_primitives"]
                          and abs(b["area_leaf_m2"] - a["area_leaf_m2"]) < 1e-9
                          and abs(b["area_fruit_m2"] - a["area_fruit_m2"]) < 1e-9),
        })
    n_identical = sum(1 for d in deltas if d["identical"])
    log(f"  consecutive stages that are geometrically IDENTICAL: {n_identical}/{len(deltas)}")

    # -- Q2: advanceTime path vs direct-build path ---------------------------
    log(f"\n[Q2] direct build at age {grow_end_age} vs advanceTime path")
    orch_direct = build_orchard(seed=args.seed, age_days=grow_end_age)
    try:
        direct_sig = _geom_signature(orch_direct)
    finally:
        orch_direct.close()
    same = {k: (grow_end_sig.get(k) == direct_sig.get(k))
            for k in ("n_primitives", "n_leaf_prims", "n_fruit_prims", "n_shoot_prims")}
    area_diff = {k: float(abs(grow_end_sig[k] - direct_sig[k]))
                 for k in grow_end_sig if k.startswith("area_")}
    log(f"  advanceTime path: prims={grow_end_sig['n_primitives']}  "
        f"leafA={grow_end_sig['area_leaf_m2']:.4f}  fruitA={grow_end_sig['area_fruit_m2']:.4f}")
    log(f"  direct build    : prims={direct_sig['n_primitives']}  "
        f"leafA={direct_sig['area_leaf_m2']:.4f}  fruitA={direct_sig['area_fruit_m2']:.4f}")
    log(f"  count equality: {same}")
    log(f"  |area difference|: {json.dumps({k: round(v,6) for k,v in area_diff.items()})}")
    equivalent = all(same.values()) and all(v < 1e-6 for v in area_diff.values())
    log(f"  EQUIVALENT: {equivalent}")

    res = {"seed": args.seed, "start_age": args.start_age, "dt": args.dt,
           "n_steps": args.n_steps, "steps": steps, "stage_deltas": deltas,
           "n_identical_consecutive_stages": n_identical,
           "advance_time_cost_s": {"mean": float(np.mean(grow_times)),
                                    "min": float(np.min(grow_times)),
                                    "max": float(np.max(grow_times))},
           "build_cost_s": steps[0]["seconds"],
           "q2_advance_vs_build": {"count_equality": same, "area_abs_diff": area_diff,
                                    "equivalent": bool(equivalent),
                                    "advance_path": grow_end_sig, "direct_build": direct_sig}}
    with open(os.path.join(OUT_DIR, "w0c_growth_window.json"), "w") as f:
        json.dump(res, f, indent=2)
    with open(os.path.join(OUT_DIR, "w0c_log.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    log(f"\nWrote {OUT_DIR}/w0c_growth_window.json")
    return res


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import traceback
        traceback.print_exc()
        try:
            sys.path.insert(0, "/home/yogesh/PyHelios")
            from notify_slack import notify_slack
            notify_slack(f"World model W0c FAILED: {traceback.format_exc()[-1200:]}")
        except Exception:
            pass
        raise
