"""
T7.6 (D5) -- honest classical baseline: classical depth fusion with exact
poses, run for real against this phase's own real multi-view data.

Task doc: "Classical MVS / TSDF fusion / PromptDA depth completion with
exact poses. If classical wins, that IS the finding."

## What this reuses, and why

Phase 4's `occupancy_map.py` (T4.1) is a real, self-contained, numpy-only
log-odds volumetric fusion of real depth + exact poses -- a beam sensor
model (range AND angular uncertainty) integrated over many views into a
3-state (occupied/free/unknown) voxel grid. That IS a classical
depth-fusion baseline (probabilistic occupancy fusion is the same family
as TSDF fusion: both accumulate per-voxel evidence from multiple posed
depth observations; log-odds occupancy is arguably the MORE principled of
the two since it explicitly separates "empty" from "never observed"
rather than a single signed-distance value). Reimplementing a second,
independent TSDF fusion from scratch here would just be the same idea
with a different accumulator and no real reason to duplicate it -- so
this module reuses `phase4.occupancy_map`/`sensor_model` directly against
Phase 7's OWN real rendered data (a fresh tree, fresh views, generated by
`render_utils.py`, not Phase 4's dataset), rather than re-deriving fusion
math Phase 4 already validated.

No opencv/open3d/pycolmap/COLMAP binary is installed in this env (see
PHASE7_LOG.md) -- a "real classical MVS" in the patch-match-stereo sense
(dense stereo matching + bundle adjustment) was explicitly out of scope
per the task's own guidance ("numpy/scipy-based multi-view stereo or
simple depth fusion is fine -- doesn't need heavyweight external
packages"). Depth fusion WITH EXACT POSES (this Context already gives
exact K/R/t for every view -- no pose estimation needed here at all,
unlike T7.2/T7.3) is exactly the fusion half of MVS, using Helios's own
rendered depth as the per-view "stereo" output.

Output of this module (voxel grid + occupied-voxel world centers) is
consumed directly by T7.5 (thin-structure recall by diameter class) and
T7.7 (metric-scale cross-check).
"""

import json
import os
import sys
import time

import numpy as np

from pyhelios import Context, PlantArchitecture, RadiationModel

from yogesh_dev.phase0.radiation_setup import setup_bands_and_lights
from yogesh_dev.phase1.ground_truth import enable_fruit_object_data

from yogesh_dev.phase7.render_utils import (
    RESOLUTION, VFOV_DEG, build_tree_scene, tree_lookat_and_radius, full_circle_poses,
    register_camera_pool, branch_skeleton_points, fruit_landmark_points,
)
from yogesh_dev.phase7.wai_writer import write_wai_scene

_PHASE4_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "phase4")
if _PHASE4_DIR not in sys.path:
    sys.path.insert(0, _PHASE4_DIR)  # occupancy_map.py does `import sensor_model` (bare), needs phase4/ on path

import occupancy_map as om  # noqa: E402  (phase4 module, path-injected above)
import sensor_model as sm  # noqa: E402

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")
WAI_ROOT = os.path.join(OUTPUT_DIR, "wai_dataset")
N_VIEWS_PER_RING = 14
ELEVATIONS_DEG = [-5.0, 20.0, 40.0]  # 3 rings -> decent vertical coverage, not just one equator orbit
TREE_AGE_DAYS = 720.0
COARSE_VOXEL_M = 0.02   # matches the "every published benchmark measured at 5cm" literature regime (rounded)
FINE_VOXEL_M = 0.005
SCENE_MARGIN_M = 0.15
PIXEL_STRIDE = 2  # matches Phase 4's own tractability choice (T4.2 update-time sweep)


def _multi_ring_poses(lookat, radius, n_per_ring, elevations_deg):
    poses, azs, elevs = [], [], []
    for elev in elevations_deg:
        p, a = full_circle_poses(lookat, radius, n_per_ring, elevation_deg=elev)
        poses.extend(p)
        azs.extend(a)
        elevs.extend([elev] * len(a))
    return poses, azs, elevs


def run(seed=0):
    with Context() as context:
        with PlantArchitecture(context) as plantarch:
            enable_fruit_object_data(plantarch)
            plant_id, position, all_uuids = build_tree_scene(context, plantarch, age_days=TREE_AGE_DAYS)
            branch_pts, segments, seg_counts = branch_skeleton_points(context, all_uuids, seed=seed)
            fruit_pts = fruit_landmark_points(context, plantarch, [plant_id])
            lookat, radius, height, width = tree_lookat_and_radius(context, all_uuids, position)

            # Real ground-truth scale quantities from THIS SAME tree/Context
            # (T7.7 cross-checks these against T7.6's own reconstruction below
            # -- must be the same tree instance, not a rebuild: growth is
            # stochastic, see PHASE7_LOG.md).
            leaf_uuids = context.filterPrimitivesByData(all_uuids, "object_label", "leaf")
            leaf_area_m2_gt = sum(context.getPrimitiveArea(u) for u in leaf_uuids)
            x_b, y_b, z_b = context.getDomainBoundingBox(all_uuids)
            canopy_bbox_min = [x_b.x, y_b.x, z_b.x]
            canopy_bbox_max = [x_b.y, y_b.y, z_b.y]
            canopy_bbox_volume_m3 = (x_b.y - x_b.x) * (y_b.y - y_b.x) * (z_b.y - z_b.x)
            shoot_lengths_m = [float(np.linalg.norm(np.array(s["p1"]) - np.array(s["p0"])))
                                for s in segments if s["label"] == "shoot"]
            mean_internode_length_m_gt = float(np.mean(shoot_lengths_m)) if shoot_lengths_m else None
            poses, azs_deg, elevs_deg = _multi_ring_poses(lookat, radius, N_VIEWS_PER_RING, ELEVATIONS_DEG)
            n_views = len(poses)

            with RadiationModel(context) as radiation:
                setup_bands_and_lights(radiation)
                labels, hfov_deg = register_camera_pool(radiation, n_views)
                radiation.updateGeometry()

                for label, (eye, lk) in zip(labels, poses):
                    radiation.setCameraPosition(label, eye)
                    radiation.setCameraLookat(label, lk)
                radiation.runBand(["red", "green", "blue"])

                extra = [{"azimuth_deg": float(a), "elevation_deg": float(e), "plant_id": plant_id}
                         for a, e in zip(azs_deg, elevs_deg)]
                scene_meta = write_wai_scene(
                    radiation, labels, poses, hfov_deg, RESOLUTION, WAI_ROOT,
                    dataset_name="helios_apple_tree", scene_name="tree_t76_mvs_rig",
                    write_rgb=True, write_depth=True, write_semantic_mask=False,
                    extra_frame_fields=extra,
                )

    scene_dir = os.path.join(WAI_ROOT, "helios_apple_tree", "tree_t76_mvs_rig")
    intr = sm.intrinsics(RESOLUTION, vfov_deg=VFOV_DEG)

    def read_depth(path):
        import OpenEXR
        f = OpenEXR.File(path)
        ch = f.channels()
        key = "Z" if "Z" in ch else next(iter(ch.keys()))
        return np.array(ch[key].pixels, dtype=np.float32)

    gt_points_all = np.array(
        [p["point"] for p in branch_pts] + [p["point"] for p in fruit_pts]
    )
    scene_bmin = gt_points_all.min(axis=0) - SCENE_MARGIN_M
    scene_bmax = gt_points_all.max(axis=0) + SCENE_MARGIN_M

    def fuse(voxel_m):
        grid = om.make_grid(scene_bmin, scene_bmax, voxel_m)
        t0 = time.time()
        n_pix_total = 0
        for frame in scene_meta["frames"]:
            depth = read_depth(os.path.join(scene_dir, frame["depth_path"]))
            om.integrate_view(grid, [], frame["eye"], frame["lookat"], depth, intr,
                               pixel_stride=PIXEL_STRIDE)
            n_pix_total += int(np.sum(depth != sm.SKY_DEPTH_SENTINEL))
        elapsed = time.time() - t0
        counts = grid.counts()
        return grid, {"voxel_m": voxel_m, "dims": list(grid.dims), "counts": counts,
                       "fusion_time_s": elapsed, "n_valid_pixels_total": n_pix_total}

    grid_coarse, report_coarse = fuse(COARSE_VOXEL_M)
    grid_fine, report_fine = fuse(FINE_VOXEL_M)

    def occupied_world_centers(grid):
        state = grid.state_grid()
        idx = np.argwhere(state == 2)
        centers = grid.bmin[None, :] + (idx + 0.5) * grid.voxel_size
        return centers

    centers_coarse = occupied_world_centers(grid_coarse)
    centers_fine = occupied_world_centers(grid_fine)
    np.save(os.path.join(OUTPUT_DIR, "t76_occupied_centers_coarse.npy"), centers_coarse)
    np.save(os.path.join(OUTPUT_DIR, "t76_occupied_centers_fine.npy"), centers_fine)

    # Also save as sparse occupied-index grids (bmin/voxel_size + boolean
    # occupied array) -- T7.5's diameter-class recall does a voxel-index
    # neighborhood lookup rather than an O(segments x occupied_voxels)
    # brute-force distance matrix (which would be multi-GB at this
    # resolution), so it needs the grid structure, not just point clouds.
    np.savez_compressed(os.path.join(OUTPUT_DIR, "t76_grid_coarse.npz"),
             occupied=(grid_coarse.state_grid() == 2), bmin=grid_coarse.bmin,
             voxel_size=grid_coarse.voxel_size)
    np.savez_compressed(os.path.join(OUTPUT_DIR, "t76_grid_fine.npz"),
             occupied=(grid_fine.state_grid() == 2), bmin=grid_fine.bmin,
             voxel_size=grid_fine.voxel_size)

    # Persisted so T7.5 (diameter-class recall) analyzes THIS SAME tree's real
    # branch segments against THIS SAME reconstruction, rather than rebuilding
    # a tree (growth is stochastic -- see PHASE7_LOG.md -- so a rebuild would
    # silently be a different skeleton).
    with open(os.path.join(OUTPUT_DIR, "t76_branch_segments.json"), "w") as f:
        json.dump(segments, f, indent=2)

    ground_truth_scale = {
        "leaf_area_m2": leaf_area_m2_gt,
        "canopy_bbox_min": canopy_bbox_min, "canopy_bbox_max": canopy_bbox_max,
        "canopy_bbox_volume_m3": canopy_bbox_volume_m3,
        "mean_internode_length_m": mean_internode_length_m_gt,
        "n_internode_shoot_segments": len(shoot_lengths_m),
        "fruit": [{"point": p["point"].tolist(), "diameter_m": p["diameter_m"]} for p in fruit_pts],
        "mean_fruit_diameter_m": float(np.mean([p["diameter_m"] for p in fruit_pts])) if fruit_pts else None,
    }
    with open(os.path.join(OUTPUT_DIR, "t76_ground_truth_scale.json"), "w") as f:
        json.dump(ground_truth_scale, f, indent=2, default=float)

    # Direct accuracy check: for every real landmark (branch midpoint / fruit
    # centroid), is there an occupied fine-grid voxel within ~its own radius?
    # This is the honest "did classical fusion recover this known point"
    # check -- reused by T7.5 for the diameter-class breakdown.
    def nearest_occupied_dist(centers, query_pts):
        if len(centers) == 0:
            return np.full(len(query_pts), np.inf)
        d = np.linalg.norm(centers[None, :, :] - query_pts[:, None, :], axis=2)
        return d.min(axis=1)

    branch_gt = np.array([p["point"] for p in branch_pts])
    branch_radii_m = np.array([p["diameter_mm"] for p in branch_pts]) / 2000.0
    dists_fine = nearest_occupied_dist(centers_fine, branch_gt)
    hit_fine = dists_fine <= (branch_radii_m + FINE_VOXEL_M)
    fruit_gt = np.array([p["point"] for p in fruit_pts]) if fruit_pts else np.zeros((0, 3))
    fruit_radii_m = np.array([p["diameter_m"] / 2.0 for p in fruit_pts]) if fruit_pts else np.zeros((0,))
    dists_fruit = nearest_occupied_dist(centers_fine, fruit_gt) if len(fruit_gt) else np.array([])
    hit_fruit = dists_fruit <= (fruit_radii_m + FINE_VOXEL_M) if len(fruit_gt) else np.array([], dtype=bool)

    report = {
        "seed": seed, "n_views": n_views, "n_views_per_ring": N_VIEWS_PER_RING,
        "elevations_deg": ELEVATIONS_DEG, "hfov_deg": hfov_deg, "resolution": list(RESOLUTION),
        "pixel_stride": PIXEL_STRIDE, "scene_margin_m": SCENE_MARGIN_M,
        "wai_scene_dir": os.path.relpath(scene_dir, os.path.dirname(__file__)),
        "branch_segment_counts": seg_counts, "n_branch_landmarks": len(branch_pts),
        "n_fruit_landmarks": len(fruit_pts),
        "fusion_coarse": report_coarse, "fusion_fine": report_fine,
        "branch_recovery_rate_fine_grid": float(np.mean(hit_fine)) if len(hit_fine) else None,
        "fruit_recovery_rate_fine_grid": float(np.mean(hit_fruit)) if len(hit_fruit) else None,
        "occupied_centers_coarse_path": "t76_occupied_centers_coarse.npy",
        "occupied_centers_fine_path": "t76_occupied_centers_fine.npy",
        "n_occupied_voxels_coarse": len(centers_coarse), "n_occupied_voxels_fine": len(centers_fine),
        "scene_bmin": scene_bmin.tolist(), "scene_bmax": scene_bmax.tolist(),
    }
    return report


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    report = run()
    out_path = os.path.join(OUTPUT_DIR, "t76_classical_baseline.json")
    with open(out_path, "w") as f:
        json.dump(report, f, indent=2, default=float)
    print(json.dumps({k: v for k, v in report.items()
                       if k not in ("scene_bmin", "scene_bmax")}, indent=2))
    print("wrote", out_path)
    return report


if __name__ == "__main__":
    main()
